version: '3.8'

services:
  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - ${PREFIX}/docker-infra/domotica/data:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/smart_meter:/dev/smart_meter
    networks:
      - outside
    deploy:
      # homeassistant is not exposed to Traefik via labels.
      # See: https://github.com/traefik/traefik/issues/5535
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  zwave:
    image: zwavejs/zwavejs2mqtt
    volumes:
      - zwavejs:/usr/src/app/store
      - /dev/zwave:/dev/zwave
    networks:
      - infra-network_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.zwavejs.loadbalancer.server.port=8091
        - traefik.http.routers.zwavejs.entrypoints=https
        - traefik.http.routers.zwavejs.tls=true
        - traefik.http.routers.zwavejs.tls.certresolver=letsencrypt
        - traefik.http.routers.zwavejs.service=zwavejs

        - traefik.http.services.zwavews.loadbalancer.server.port=3000
        - traefik.http.routers.zwavews.rule=Host(`zwavews.ronj.nl`)
        - traefik.http.routers.zwavews.entrypoints=http
        - traefik.http.routers.zwavews.priority=2000
        - traefik.http.routers.zwavews.service=zwavews
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  infra-network_public:
    external: true
  outside:
    external:
      name: host

volumes:
  zwavejs:

